filetype plugin indent on
syntax on

set packpath=~/.dotfiles/vim/

"Who likes swap files?
set noswapfile

" custom color scheme
colorscheme custom

" remove trailing whitespaces on :w
autocmd BufWritePre * %s/\s\+$//e

" add paste toggle
set pastetoggle=<F2>


" fix bad splits with ctrl hjkl
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

set splitbelow
set splitright

"make into a real editor
syntax on
syntax enable
set autoindent
set tabstop=4
set softtabstop=4 expandtab
set shiftwidth=4
set expandtab
set ai
set number
set hlsearch
set ruler
set wrap!
highlight Comment ctermfg=green

"make into vim
noremap <Up> <Nop>
noremap <Down> <Nop>
noremap <Left> <Nop>
noremap <Right> <Nop>

