require('onedark').setup()
vim.cmd[[colorscheme onedark]]

-- vim.cmd[[highlight Normal guibg=NONE ctermbg=NONE guifg=NONE ctermfg=NONE]]
-- vim.cmd[[highlight NonText guibg=NONE ctermbg=NONE]]
-- vim.cmd[[highlight StatusLine ctermbg=NONE guibg=#3b4252]]
-- vim.cmd[[highlight StatusLine ctermfg=NONE ctermbg=NONE guibg=NONE guifg=NONE]]
-- vim.cmd[[highlight StatusLineNC ctermfg=NONE ctermbg=NONE guibg=NONE guifg=NONE]]
-- vim.cmd[[highlight StatusLineTerm ctermfg=NONE ctermbg=NONE guibg=NONE guifg=NONE]]
-- vim.cmd[[highlight StatusLineTermNC ctermfg=NONE ctermbg=NONE guibg=NONE guifg=NONE]]
-- vim.cmd[[highlight TabLineFill ctermfg=NONE ctermbg=NONE guibg=NONE guifg=NONE]]
vim.cmd[[highlight LineNr ctermfg=NONE ctermbg=NONE guibg=NONE guifg=#ffbfee]]
vim.cmd[[highlight BufferInactiveMod ctermfg=NONE ctermbg=NONE guibg=NONE guifg=NONE]]
vim.cmd[[highlight BufferCurrent ctermfg=NONE ctermbg=NONE guibg=NONE guifg=NONE]]
vim.cmd[[highlight BufferTabpageFill ctermfg=NONE ctermbg=NONE guibg=NONE guifg=NONE]]
--vim.cmd[[highlight VertSplit guibg=NONE guifg=#3b4252 ctermbg=NONE ctermfg=NONE]]
-- vim.cmd[[highlight PMENU guibg=#3B4252]]
--[[ vim.cmd[[highlight NvimTreeNormal guibg=NONE]]
--vim.cmd[[highlight NvimTreeVertSplit guibg=NONE]]
-- vim.cmd[[highlight NvimTreeEndOfBuffer guibg=NONE]]

