#!/bin/bash
case $BLOCK_BUTTON in
	1) setsid "$TERMINAL" -e pulsemixer & ;;
	2) pulsemixer --toggle-mute ;;
	4) pulsemixer --change-volume +5 ;;
	5) pulsemixer --change-volume -5 ;;
	3) pgrep -x dunst >/dev/null && notify-send "<b> Volume module:</b>
- Shows volume 🔊, 🔇 if muted.
- Middle click to mute.
- Scroll to change."
esac

[ "$(pulsemixer --get-mute)" = "1" ] && printf "" && exit

vol=$(pulsemixer --get-volume | awk '{print $1}')

if [ "$vol" -gt "70" ]; then
	icon=""
elif [ "$vol" -lt "30" ]; then
	icon=""
else
	icon=""
fi

printf "%s %s%%" "$icon" "$vol"
